export enum ErrorCode {
	INTERNAL_SERVER_ERROR = 'Internal server error',
	UNAUTHORIZED = 'Unauthorized',
	INVALID_PERMISSION = 'Invalid permission',
	INCORRECT_EMAIL_PASSWORD = 'Incorrect email or password',
	USER_NOT_FOUND = 'User not found',
	EMAIL_EXISTS = 'Email already exists',
	USER_EXIST = 'User already exists',
	NOT_PERMITTED_ROLE = 'Not permitted role',
	USER_IN_ACTIVE = 'User in active',
	INCORRECT_CURRENT_PASSWORD = 'Incorrect current password',
	INVALID_OTP = 'Invalid OTP',
	EMAIL_NOT_FOUND = 'Email not found',

	STATE_NOT_FOUND = 'State not found',
	CITY_NOT_FOUND = 'City not found',
	CATEGORY_NOT_FOUND = 'Category not found',
	SPORT_NOT_FOUND = 'Sport not found',
	SEASON_NOT_FOUND = 'Season not found',
	SCHOOL_DISTRICT_NOT_FOUND = 'School district not found',
	SCHOOL_NOT_FOUND = 'School not found',
	BOOSTER_NOT_FOUND = 'Booster not found',
	EVENT_NOT_FOUND = 'Event not found',
	PRODUCT_NOT_FOUND = 'Product not found',
	PRODUCT_UNAVAILABLE = 'Product unavailable',
	PHONE_ALREADY_EXISTS = 'Phone already exists',
	ORDER_NOT_FOUND = 'Order not found',
	ORDER_ITEM_NOT_FOUND = 'Order item not found',
	WORKER_ALREADY_ADDED_TO_EVENT = 'Worker already added to event',
	WORKER_NOT_FOUND_IN_EVENT = 'Worker not found in event',
}
